[theme]
theme = "gruvbox-dark"
[theme.overrides]
info_bg = "#b57614"
[icons]
icons = "awesome6"

[[block]]
block = "cpu"
interval = 1

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"

# [[block]]
# block = "temperature"
# collapsed = false
# interval = 5
# format = "{max}"
# chip = "k10temp-pci-00c3"
# inputs = ["Tctl","Tdie"]
# driver="sensors"
# info = 75
# idle = 75
# [block.theme_overrides]
# info_bg = "#282828"
# idle_bg = "#282828"

# [[block]]
# block = "nvidia_gpu"
# show_memory = false
# show_utilization = false
# label = ""
# interval = 1

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%d/%m %R') "
