icons = "awesome"

[theme]
name = "gruvbox-dark"
[theme.overrides]
info_bg = "#b57614"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
max_width = 50
on_click="i3-msg -t command 'workspace 10'"
[block.theme_overrides]
info_bg = "#484E50"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
interval = 5
format = "{max}"
chip = "k10temp-pci-00c3"
inputs = ["Tctl","Tdie"]
driver="sensors"
info = 75
idle = 75
[block.theme_overrides]
info_bg = "#282828"
idle_bg = "#282828"

[[block]]
block = "nvidia_gpu"
show_memory = false
show_utilization = false
label = ""
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

